AWSTemplateFormatVersion: 2010-09-09

Parameters:

  TaskSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet to launch the task into"

  TaskSg:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "SG to attach to the task"

Resources:

  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/fyp-ddb-load-tester"

  ECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "fyp-ddb-stress-test"

  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Cpu: "256"
      Memory: "0.5GB"
      NetworkMode: "awsvpc"
      ExecutionRoleArn: !Ref FargateExecutionRole
      TaskRoleArn: !Ref FargateDDBTaskRole
      RequiresCompatibilities:
        - "FARGATE"
      ContainerDefinitions:
        - Name: "fyp-ddb-stress-test"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/fyp-ddb-stress-test:latest"
          WorkingDirectory: /tmp/workdir
          Essential: "true"
          Environment:
            - Name: WRITE_STRESS_CONFIG
              Value: "-sw -wcu 5"
            - Name: READ_STRESS_CONFIG
              Value: "-sr -rcu 5"
            - Name: TABLE_REGION
              Value: us-east-1
            - Name: TABLE_NAME
              Value: MyTable2
            - Name: HASH_KEY
              Value: MyKey
            - Name: DURATION
              Value: 300
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/fyp-ddb-load-tester
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  LoadTestLauncher:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.lambda_handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          from __future__ import print_function
          import json
          import boto3

          ecs = boto3.client('ecs', region_name='${AWS::Region}')

          def lambda_handler(event, context):

              # Log the received event
              print("Received event: " + json.dumps(event, indent=2))

              # Check we have the required event properties to continue
              expected_fields = ["tableRegion", "tableName", "hashKey", "duration"]
              for f in expected_fields:
                  if f not in event:
                      print("Expecting field {} in event data. Exiting.".format(f))
                      exit(1)

              read_stress_config = ""
              write_stress_config = ""

              if "stressRead" in event and event["stressRead"] is True:
                  if "rcu" not in event:
                      print("Expecting rcu in event data. Exiting.".format(f))
                      exit(1)
                  read_stress_config = "-sr -rcu {}".format(event["rcu"])

              if "stressWrite" in event and event["stressWrite"] is True:
                  if "rcu" not in event:
                      print("Expecting wcu in event data. Exiting.".format(f))
                      exit(1)
                  write_stress_config = "-sw -wcu {}".format(event["wcu"])

              if read_stress_config == "" and write_stress_config == "":
                  print("No stressRead or stressWrite flags given")
                  exit(1)

              try:
                  response = ecs.run_task(
                      cluster='default',
                      taskDefinition='${TaskDefinition}',
                      overrides={
                          'containerOverrides': [
                              {
                                  'name': 'fyp-ddb-stress-test',
                                  'environment': [
                                      {
                                          'name': 'WRITE_STRESS_CONFIG',
                                          'value': str(write_stress_config)
                                      },
                                      {
                                          'name': 'READ_STRESS_CONFIG',
                                          'value': str(read_stress_config)
                                      },
                                      {
                                          'name': 'TABLE_REGION',
                                          'value': str(event['tableRegion'])
                                      },
                                      {
                                          'name': 'TABLE_NAME',
                                          'value': str(event['tableName'])
                                      },
                                      {
                                          'name': 'HASH_KEY',
                                          'value': str(event['hashKey'])
                                      },
                                      {
                                          'name': 'DURATION',
                                          'value': str(event['duration'])
                                      },
                                  ]
                              },
                          ]
                      },
                      launchType='FARGATE',
                      platformVersion='LATEST',
                      networkConfiguration={
                          'awsvpcConfiguration': {
                              'subnets': [
                                  '${TaskSubnet}',
                              ],
                              'securityGroups': [
                                  '${TaskSg}',
                              ],
                              'assignPublicIp': 'ENABLED'
                          }
                      }
                  )
                  print(response)
                  return True
              except Exception as e:
                  print(e)
                  message = 'Error starting task'
                  print(message)
                  raise Exception(message)

      Runtime: "python3.6"
      Timeout: "25"


  FargateExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"
          - Effect: Allow
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
            Resource: "*"

  FargateDDBTaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
            Resource: "*"

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - "logs:*"
              - "ecs:RunTask"
            Resource: "*"
          - Effect: Allow
            Action: "iam:PassRole"
            Resource:
              - !GetAtt FargateDDBTaskRole.Arn
              - !GetAtt FargateExecutionRole.Arn
